spring.application.name=Contact_manager
spring.datasource.username=root
spring.datasource.password=Rutuja@24
spring.datasource.url=jdbc:mysql://localhost:3306/Contacts

#for creating tables automatically and update fast
spring.jpa.hibernate.ddl-auto=update
#for jpa configrations
spring.jpa.show-sql=true 
server.port=8081

spring.jpa.properties.hibernate.formate_sql=true;