spring.security.oauth2.client.registration.google.client-id=617977637528-emm0oscnjgo8nnqodvthtsn2qcpijg5u.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.github.client-id=Ov23li85MKSPXlquNM0n
spring.security.oauth2.client.registration.github.client-secret=8605805173d8bbc65fc6b6dfd6977ed52d0ca74a
spring.security.oauth2.client.registration.github.scope=email,profile

cloudinary.api.key=196414294576544
cloudinary.api.secret=196414294576544
cloudinary.cloud.name=dvn7ivirj

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rutujadatir09@gmail.com
spring.mail.password=zzomgbowhzjavbgk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true